### Handling imbalanced Dataset 
-> In our Dataset if there are 1000 samples and dataset has categorical values like 'Yes' and 'No'. 
-> Now the main thing is; if in this Dataset the 900 are 'Yes' and only 100 are 'No' Data and on this Data if we train our model then our model prediction go for biased decision.
-> Either we have to decrease 900yes data or we can improve 100no data; so that our model prediction is no more biased base. 
-> For that we use "Up scaling" and "Down Scaling".

## Handling Imbalanced Dataset

1. Up Sampling
2. Down Sampling

In [14]:
import numpy as np
import pandas as pd

# Set the random seed for reproducibility
np.random.seed(123) # set the seed

# print(np.random.randint(100))  # bcs we set the seed it always returns the same number

# creating dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [15]:
n_class_0,n_class_1

(900, 100)

In [16]:
# Creating DataFrame with Imbalanced data-set

# loc = Mean (“centre”) of the distribution.
# scale = Standard deviation (spread or “width”) of the distribution. Must be non-negative.

class_0 = pd.DataFrame({
    'feature-1': np.random.normal(loc=0, scale=1, size=n_class_0), 
    'feature-2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature-1': np.random.normal(loc=0, scale=1, size=n_class_1),
    'feature-2': np.random.normal(loc=0, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [17]:
df = pd.concat([class_0, class_1]).reset_index(drop=True)
df.head()

   feature-1  feature-2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [18]:
df.tail()

     feature-1  feature-2  target
995  -0.623629   0.845701       1
996   0.239810  -1.119923       1
997  -0.868240  -0.359297       1
998   0.902006  -1.609695       1
999   0.697490   0.013570       1

In [19]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

## UP-SAMPLING

In [20]:
df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

In [28]:
from sklearn.utils import resample

df_minority_upsampled = resample(df_minority, replace=True, # Sample with replacement
                                n_samples = len(df_majority),
                                 random_state = 42    # setting state gives us the best same output as we set seed 
                                )

In [29]:
df_minority_upsampled.shape

(900, 3)

In [30]:
df_minority_upsampled.head()

     feature-1  feature-2  target
951   0.357491   0.323514       1
992   1.071255  -0.021295       1
914  -1.081192  -0.265183       1
971   0.086091   0.117100       1
960   0.797611  -1.121086       1

In [32]:
df_upsampled = pd.concat([df_majority, df_minority_upsampled])

In [33]:
df_upsampled

     feature-1  feature-2  target
0    -0.460530   1.131538       0
1    -0.910269  -0.321510       0
2    -0.780990   0.392148       0
3    -0.107118  -0.541998       0
4    -0.657885  -1.513386       0
..         ...        ...     ...
952   0.495822   1.442561       1
965   0.117276   1.605320       1
976   1.397362  -1.749817       1
942  -0.149407   2.018072       1
974   0.490092   0.193099       1

[1800 rows x 3 columns]

In [37]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

## DOWN-SAMPLING

In [39]:
import pandas as pd

# Setting random seed for reproductivity
np.random.seed(123)

# create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [55]:
# Making DataFrames

class_0 = pd.DataFrame({
    'feature-1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature-2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})
class_1 = pd.DataFrame({
    'feature-1': np.random.normal(loc=0, scale=1, size=n_class_1),
    'feature-2': np.random.normal(loc=0, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [56]:
df = pd.concat([class_0, class_1]).reset_index(drop=True)
df.head()

   feature-1  feature-2  target
0   1.586350   1.498609       0
1   0.798713  -0.172506       0
2  -0.983213   0.558718       0
3   0.085812   0.145188       0
4   0.536751   0.392016       0

In [57]:
df.tail()

     feature-1  feature-2  target
995  -0.319121  -0.537154       1
996   1.441003   0.486713       1
997  -0.908636   1.006645       1
998   2.644096   0.323907       1
999  -0.687047  -0.207907       1

In [60]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [62]:
## downsampling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [64]:
from sklearn.utils import resample

df_majority_downsampled = resample(df_majority, 
                                  n_samples = len(df_minority),
                                  random_state = 42)

In [66]:
df_majority_downsampled.shape

(100, 3)

In [67]:
df_majority_downsampled.head()

     feature-1  feature-2  target
102  -1.404975  -0.585283       0
435  -0.285087   0.314140       0
860  -1.433796  -0.361965       0
270   0.190852   1.669518       0
106  -0.477546  -1.011353       0

In [68]:
df_downsampled = pd.concat([df_minority, df_majority_downsampled])

In [73]:
df_downsampled['target'].value_counts()

target
1    100
0    100
Name: count, dtype: int64