## Target Guided Ordinal Encoding 
It is a technique used to encode categorical variables based on their relationship with the target variable. This encoding technique is useful when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine learning model.

In Target Guided Ordinal Encoding, we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable for that category. This creates a monotonic relationship between the categorical variable and the target variable, which can improve the predictive power of our model.

In [1]:
import pandas as pd

# Create an sample DataFrame with a categorical variabl and a target variable
df = pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200,150,300,250,180,320]
})

In [2]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [6]:
mean_price = df.groupby('city')['price'].mean().to_dict()
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [7]:
df['city_encoded'] = df['city'].map(mean_price)

In [8]:
df

       city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0

In [10]:
df[['price', 'city_encoded']] 
# Now for model training we can use 'city_encoded' column and our model give importance based on number. 
# If the number is higher then it get more priority and as small it is; it consider as less valueable.

   price  city_encoded
0    200         190.0
1    150         150.0
2    300         310.0
3    250         250.0
4    180         190.0
5    320         310.0

In [12]:
# Exercise

In [17]:
import seaborn as sns
df = sns.load_dataset('tips')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [20]:
mean_bill = df.groupby('tip')['total_bill'].mean().to_dict()
mean_bill

{1.0: 7.1675,
 1.01: 16.99,
 1.1: 12.9,
 1.17: 32.83,
 1.25: 9.696666666666667,
 1.32: 9.68,
 1.36: 18.64,
 1.44: 7.65,
 1.45: 9.55,
 1.47: 10.77,
 1.48: 8.52,
 1.5: 14.158888888888889,
 1.56: 9.94,
 1.57: 15.42,
 1.58: 13.42,
 1.61: 10.59,
 1.63: 11.87,
 1.64: 15.36,
 1.66: 10.34,
 1.67: 10.33,
 1.68: 13.42,
 1.71: 10.27,
 1.73: 9.78,
 1.75: 17.82,
 1.76: 11.24,
 1.8: 12.43,
 1.83: 10.07,
 1.92: 8.58,
 1.96: 15.04,
 1.97: 12.02,
 1.98: 11.02,
 2.0: 15.798787878787879,
 2.01: 16.485,
 2.02: 15.48,
 2.03: 20.125,
 2.05: 28.55,
 2.09: 15.01,
 2.18: 22.82,
 2.2: 13.445,
 2.23: 14.265,
 2.24: 18.4,
 2.3: 16.43,
 2.31: 15.190000000000001,
 2.34: 17.81,
 2.45: 20.69,
 2.47: 16.45,
 2.5: 17.347,
 2.52: 12.48,
 2.54: 17.46,
 2.55: 23.95,
 2.56: 28.44,
 2.6: 10.29,
 2.61: 13.39,
 2.64: 17.59,
 2.71: 17.29,
 2.72: 13.28,
 2.74: 17.26,
 2.75: 16.725,
 2.83: 20.27,
 2.88: 22.12,
 2.92: 24.08,
 3.0: 21.68,
 3.02: 14.83,
 3.06: 13.94,
 3.07: 16.93,
 3.08: 17.92,
 3.09: 30.14,
 3.11: 32.9,
 3.12: 26.88,
 3.14: 26.86,
 3.15: 20.08,
 3.16: 15.81,
 3.18: 25.835,
 3.21: 20.29,
 3.23: 15.625,
 3.25: 20.505000000000003,
 3.27: 17.78,
 3.31: 23.68,
 3.35: 20.65,
 3.39: 11.61,
 3.4: 16.66,
 3.41: 26.59,
 3.48: 20.12,
 3.5: 22.349999999999998,
 3.51: 19.49,
 3.55: 34.63,
 3.6: 24.06,
 3.61: 24.59,
 3.68: 34.65,
 3.71: 16.29,
 3.75: 25.0,
 3.76: 18.265,
 3.92: 21.58,
 4.0: 21.349166666666665,
 4.06: 20.49,
 4.08: 19.42,
 4.19: 19.81,
 4.2: 29.8,
 4.29: 25.21,
 4.3: 19.009999999999998,
 4.34: 25.56,
 4.5: 31.71,
 4.67: 35.83,
 4.71: 25.29,
 4.73: 40.17,
 5.0: 32.693,
 5.07: 29.93,
 5.14: 29.85,
 5.15: 7.25,
 5.16: 25.89,
 5.17: 34.83,
 5.2: 34.81,
 5.6: 30.4,
 5.65: 23.33,
 5.85: 24.71,
 5.92: 29.03,
 6.0: 32.4,
 6.5: 25.67,
 6.7: 34.3,
 6.73: 48.27,
 7.58: 39.42,
 9.0: 48.33,
 10.0: 50.81}

In [22]:
df['encoded_bill'] = df['tip'].map(mean_bill)
df

     total_bill   tip     sex smoker   day    time  size  encoded_bill
0         16.99  1.01  Female     No   Sun  Dinner     2     16.990000
1         10.34  1.66    Male     No   Sun  Dinner     3     10.340000
2         21.01  3.50    Male     No   Sun  Dinner     3     22.350000
3         23.68  3.31    Male     No   Sun  Dinner     2     23.680000
4         24.59  3.61  Female     No   Sun  Dinner     4     24.590000
..          ...   ...     ...    ...   ...     ...   ...           ...
239       29.03  5.92    Male     No   Sat  Dinner     3     29.030000
240       27.18  2.00  Female    Yes   Sat  Dinner     2     15.798788
241       22.67  2.00    Male    Yes   Sat  Dinner     2     15.798788
242       17.82  1.75    Male     No   Sat  Dinner     2     17.820000
243       18.78  3.00  Female     No  Thur  Dinner     2     21.680000

[244 rows x 8 columns]

In [23]:
# So you can see that encoded-bill allign with some total-bill mean values